version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: services-frontend
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8001:80"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: services-backend
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./backend/services.json
        target: /app/services.json
        read_only: false
    networks:
      - app-network
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge